apiVersion: apps/v1
kind: Deployment
metadata:
  name: bandcd-finder
spec:
  selector:
    matchLabels:
      app: bandcd-finder
  template:
    metadata:
      labels:
        app: bandcd-finder
    spec:
      containers:
      - name: bandcd-finder
        image: finder
        imagePullPolicy: IfNotPresent
        env:
        - name: MONGO_URL
          value: "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
        args: ["--use_saved_tags", "True"]
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 8.8.8.8